### PR TITLE
Convert plugin class to Java

### PR DESCRIPTION
**Pull request by DPUkyle**
No functional changes.

Groovy is great for tests, but I prefer Java for production code.

Updated CI config to build with openjdk11, but still produces java 8 bytecode.

Finally, tweaked `.gitignore` to stop tracking IntelliJ metadata.

### CODE REVIEW

**Comment by DPUkyle** [comment]
@googlebot I signed it!

**Comment by ejona86** [comment]
Yeah, Gradle has been replacing a lot of Groovy with Java for performance.

**Comment by DPUkyle** [comment]
> Yeah, Gradle has been replacing a lot of Groovy with Java for performance.

Thanks Eric. Performance and type-safety... nice concepts! 😄

**Comment by voidzcy** [comment]
Thanks for your contribution. Would you mind to change the [test](https://github.com/google/osdetector-gradle-plugin/blob/master/src/test/groovy/com/google/gradle/osdetector/OsDetectorPluginTest.groovy) as well? It should be fairly easy.

**Comment by DPUkyle** [comment]
> Thanks for your contribution. Would you mind to change the [test](https://github.com/google/osdetector-gradle-plugin/blob/master/src/test/groovy/com/google/gradle/osdetector/OsDetectorPluginTest.groovy) as well? It should be fairly easy.

Actually I suggest leaving tests in Groovy - that's because you don't have the "gap" between compile-time and runtime that you do with production Groovy code.

If you like, I could convert the test to use the [spock framework](http://spockframework.org/), which is the _de facto_ standard for Gradle plugin testing. It uses nice given/when/then triplets to organize information. However, the code will still be written in Groovy.

**Comment by voidzcy** [comment]
> Actually I suggest leaving tests in Groovy - that's because you don't have the "gap" between compile-time and runtime that you do with production Groovy code.
> 
> If you like, I could convert the test to use the [spock framework](http://spockframework.org/), which is the _de facto_ standard for Gradle plugin testing. It uses nice given/when/then triplets to organize information. However, the code will still be written in Groovy.

Alright. Sounds fair to leave test as is.

**Pull request merged**
